---
title: "Friends Analysis Report"
author: "Callum Orkney"
date: "13/12/2020"
output: github_document
---

``` {r packages, echo = FALSE, message = FALSE}
library(tidytuesdayR)
library(dplyr)
library(forcats)
library(tidytext)
library(stringr)
library(ggplot2)
library(RcppRoll)
```


``` {r setup, echo = FALSE, message = FALSE}
# Set constants

names_six <- c('Monica Geller', 'Joey Tribbiani', 'Chandler Bing',
               'Phoebe Buffay', 'Ross Geller', 'Rachel Green')

movav_eps <- 30

# Get data

tuesdata <- tidytuesdayR::tt_load('2020-09-08')

lines <- tuesdata$friends
info <- tuesdata$friends_info
emotions <- tuesdata$friends_emotions

# Clean up lines data

lines_clean <- lines %>%
  filter(!(speaker == 'Scene Directions')) %>%
  mutate(
    speaker = as_factor(speaker),
    ep_id = paste(season, episode, sep = '-'),
    ep_id = factor(ep_id, levels = unique(ep_id)),
    ep_no = cummax(as.numeric(ep_id)),
    line_id = paste(season, episode, scene, utterance, sep = '-')
    )
```

## Analysis of number of lines
Summarising the data by episode and character, we can see how the number of lines per episode for each character has changed over time. To avoid an unreadable mess, let's calculate a 30-episode moving average:

``` {r lines-by-character}
lines_by_character <- lines_clean %>%
  filter(speaker %in% names_six) %>%
  group_by(ep_id, ep_no, speaker) %>% 
  summarise(lines = n()) %>%
  ungroup() %>% 
  group_by(speaker) %>%
  mutate(movav = roll_meanr(lines, movav_eps)) %>%
  ungroup()
```

Let's plot a line graph of this, with one line representing each character's moving average lines-per-episode over time:

``` {r line-plot, echo = FALSE, warning = FALSE}
ggplot(lines_by_character, aes(x = ep_no, y = movav, colour = speaker)) +
  geom_line() +
  labs(
    title = 'Number of lines per episode by main character',
    subtitle = paste0(movav_eps, '-episode moving averages'),
    x = 'Episode number', y = 'Lines spoken per episode',
    colour = 'Character'
  )
```



